language: node_js
node_js:
  - 'stable'
cache:
directories:
  - node_modules

install:
  - npm install

script:
  - yarn test
  - yarn run build

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
